### PR TITLE
create-connection-to-rest-api

### PR DESCRIPTION
**Pull request by danielsmcelhaney**

### CODE REVIEW

**Comment by SmokedEel** [comment]
@fredbelotte this looks good to go

**Comment by danielsmcelhaney** [comment]
I reduced the files changed in this branch from 21 to 9 now.

**Comment by danielsmcelhaney** [comment]
@fredbelotte Can this branch be approved to merge now or do more changes need to be made?

**Comment by danielsmcelhaney** [comment]
@fredbelotte Got it down to 3 files changed in this branch.  One of them is the web.charlie .csproj file.

**Comment by danielsmcelhaney** [comment]
I dropped the s from locations naming in folder,module, and service.

**Pull request merged**
